### ISSUE TITLE
Only the first shell script is linted in a list

### ISSUE THREAD

**Issue by fginther** [OddBloke/jenkins-job-linter#24]
It's possible to string together a list of shell scripts, which get rendered as individual `Execute Shell` blocks. While testing this against an existing project, I noticed that only the first entry in the list is linted.

Say I have this:

```
- builder:
    name: Awesome-Builder
    builders:
        - shell:
            !include-raw:
                - scripts/Awesome-Setup
                - scripts/Awesome-Teardown
                - scripts/Garbage
```

If `scripts/Garbage` is an empty file or has an incorrect shebang line, it's not raised as an error. If the order is changed so that `scripts/Garbage` is first in the list, errors are raised.

My expectation is that each entry in the list is a shell script and needs to confirm to the lint rules.

**Comment by OddBloke** [comment]
Thanks for the bug report! Using multiple files in an include like that concatenates them together as far as jenkins-job-builder is concerned, creating a single string. This single string is then configured in Jenkins as a single shell script, so it's correct to lint it as a single shell script. (Not only is it correct, but it would be very difficult to do otherwise.)

To expand, using your example in a job:

```yaml
- builder:
    name: Awesome-Builder
    builders:
        - shell:
            !include-raw:
                - scripts/Awesome-Setup
                - scripts/Awesome-Teardown
                - scripts/Garbage

- job:
    name: test-job
    builders:
        - Awesome-Builder
```

produces the following XML:

```xml
<?xml version="1.0" encoding="utf-8"?>
<project>
  <actions/>
  <description>&lt;!-- Managed by Jenkins Job Builder --&gt;</description>
  <keepDependencies>false</keepDependencies>
  <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
  <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
  <concurrentBuild>false</concurrentBuild>
  <canRoam>true</canRoam>
  <properties/>
  <scm class="hudson.scm.NullSCM"/>
  <builders>
    <hudson.tasks.Shell>
      <command>Awesome-Setup

Awesome-Teardown

Garbage
</command>
    </hudson.tasks.Shell>
  </builders>
  <publishers/>
  <buildWrappers/>
</project>
```

As you can see, the three includes are concatenated together and will be executed as a single shell script.

**Comment by OddBloke** [comment]
As a sidenote, it would be totally valid to do something like:

```yaml
- builder:
    name: Awesome-Builder
    builders:
        - shell:
            !include-raw:
                - scripts/Global-Shebang
                - scripts/Awesome-Setup
                - scripts/Awesome-Teardown
```

as they become a single script once compiled, and this would _require_ them to be treated as a single shell script.
