### ISSUE TITLE
Add linter to ensure that jobs referenced for triggering exist

### ISSUE THREAD

**Issue by OddBloke** [OddBloke/jenkins-job-linter#31]
In the following example, `test-1` being renamed will result in a valid JJB run, but an invalid Jenkins configuration.

```yaml
- job:
    name: test-1

- job:
    name: test-2
    builders:
        - trigger-builds:
            - project: test-1
```
